< ../config.mk

all:QV: bin/targets
	bin/targets | xargs mk

results/preprocessing_summary:Q:
	mkdir -p results/
	mkdir -p tmp/
	echo "[DEBUGGING]doing $target"
	echo "SRR_id	DOWNLOAD	MAX_PERCENTAGE_OF_READS_WITH_ADAPTER	original_reads	cutadapt_reads	uncutadapt_reads	trimmed_reads	untrimmed_reads	minimized_reads	unminimized_reads" > $target.build
	tail -n+2 $SRR_FILE | grep -v "^\$" | cut -f1 > tmp/SRRid.list
	while read p
	do
		SRR_id=$p
		DOWNLOAD_STATUS="FAIL"
		MAX_ADAPTER_PERCENTAGE="NA"
		ORIGINAL_LINES="NA"
		CUTADAPT_LINES="NA"
		UNCUTADAPT_LINES="NA"
		TRIMMED_LINES="NA"
		UNTRIMMED_LINES="NA"
		UNMINIMIZED_LINES="NA"
		MINIMIZED_LINES="NA"
		echo "[DEBUGGING]summarizing preprocessing for $SRR_id"
		if [ -f ../001/results/$SRR_id.fastq.gz ]; then
			DOWNLOAD_STATUS="OK"
			if [ -f ../002/results/$SRR_id.filtered.fasta ];then
##BELLOW, CHANGE THE TERMS OF PROCESED READS:; different versions of cutadapt have diferent trail lines to report reads procesed, etc.
##CHECK in files generated
			MAX_ADAPTER_PERCENTAGE=$(cat ../002/tmp/fastqc/$SRR_id"_fastqc"/adapter.status | cut -d" " -f2)
			ORIGINAL_LINES=$(grep -w "Total reads processed:" ../002/tmp/cutadapt/$SRR_id.cutadapt.fastq.gz.report | tr -s " " | cut -d " " -f4- | tr -d ",")
			CUTADAPT_LINES=$(grep -w "Reads with adapters:" ../002/tmp/cutadapt/$SRR_id.cutadapt.fastq.gz.report | tr -s " " | cut -d " " -f4 | tr -d ",")
			UNCUTADAPT_LINES=$(( $ORIGINAL_LINES - $CUTADAPT_LINES))
			TRIMMED_LINES=$(grep -w "Total reads processed:" ../002/tmp/minimized/$SRR_id.minimized.fastqc.report | tr -s " " | cut -d " " -f4 | tr -d ",")
			UNTRIMMED_LINES=$(( $CUTADAPT_LINES - $TRIMMED_LINES ))
			UNMINIMIZED_LINES=$(grep -w "Reads that were too long:" ../002/tmp/minimized/$SRR_id.minimized.fastqc.report | tr -s " " | cut -d " " -f6 | tr -d ",")
			MINIMIZED_LINES=$(( $TRIMMED_LINES - $UNMINIMIZED_LINES ))
			fi
		else
			echo "[WARNING] $SRR_id was not downloaded succesfully. Skipping preprocessing summarization"
		fi
		echo "$SRR_id	$DOWNLOAD_STATUS	$MAX_ADAPTER_PERCENTAGE	$ORIGINAL_LINES	$CUTADAPT_LINES	$UNCUTADAPT_LINES	$TRIMMED_LINES	$UNTRIMMED_LINES	$MINIMIZED_LINES	$UNMINIMIZED_LINES" >> $target.build
	done < tmp/SRRid.list &&
	mv $target.build $target.tsv
	