< ../config.mk

all:VQ:
	bin/targets | xargs mk

results/%.counts:Q: tmp/%.fasta_lines.tmp
	mkdir -p $(dirname $target)
	SRR_id=$(basename $target .counts )
	echo "[DEBUGGING]doing $target"
	cat $SEQUENCES_FILE | paste -sd ',\n' > tmp/$SRR_id.sequences.list
	echo "sequence_name	$(basename $target .counts)" > $target.build
	while read p
	do
		SEQUENCE_NAME=$(echo $p | cut -d"," -f1 | tr -d ">" )
		SEQUENCE=$(echo $p | cut -d"," -f2 )
		READ_COUNT=$( grep -x -c "$SEQUENCE" $prereq ) || true ##|| true allows to register when sequence had 0 matches. Otherwise, script ends with error code 1
		##echo "[DEBUGGING]sequence name is $SEQUENCE_NAME"
		##echo "[DEBUGGING]sequence is $SEQUENCE"
		##echo "[DEBUGGING]read count is $READ_COUNT"
		echo "$SEQUENCE_NAME	$READ_COUNT" >> $target.build
	done < tmp/$SRR_id.sequences.list &&
	mv $target.build $target

tmp/%.fasta_lines.tmp:Q: $SEQUENCES_FILE
	mkdir -p tmp/
	echo "[DEBUGGING]doing $target"
	grep -v "^>" data/$(basename $target .fasta_lines.tmp ).filtered.fasta > $target.build &&
	mv $target.build $target
